### ISSUE TITLE
Ao clicar em um item da tabela e tentar voltar pelo botão do navegador recebo o seguinte erro:

### ISSUE THREAD

**Issue by JaoDuque** [simbiotica-finance/bug-bounty#10]
![Captura de tela 2023-03-24 224643](https://user-images.githubusercontent.com/107492575/227679234-d1a05241-21fe-42c4-ab55-5ad013fe693c.png)

**Comment by dav1app** [comment]
Unable to reproduce. Please record a video. Provide exaclty the one item you are clicking.

**Comment by dav1app** [comment]
TypeError: Cannot convert undefined or null to object
[website] [2023-03-27 14:27:47]     at Function.values (<anonymous>)
[website] [2023-03-27 14:27:47]     at asArray (/workspace/.next/server/chunks/6504.js:41:19)
[website] [2023-03-27 14:27:47]     at processor (/workspace/.next/server/chunks/897.js:20:72)
[website] [2023-03-27 14:27:47]     at runMicrotasks (<anonymous>)
[website] [2023-03-27 14:27:47]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[website] [2023-03-27 14:27:47]     at async Promise.all (index 30)
[website] [2023-03-27 14:27:47] GET https://pro-api.coinmarketcap.com/v2/cryptocurrency/info?slug=...
[website] [2023-03-27 14:27:47] GET https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?skip_invalid=t...
[website] [2023-03-27 14:27:47] {
[website] [2023-03-27 14:27:47]   params: { slug: '' },
[website] [2023-03-27 14:27:47]   err: TypeError: Cannot convert undefined or null to object
[website] [2023-03-27 14:27:47]       at Function.values (<anonymous>)
[website] [2023-03-27 14:27:47]       at /workspace/.next/server/chunks/6543.js:91:32
[website] [2023-03-27 14:27:47]       at runMicrotasks (<anonymous>)
[website] [2023-03-27 14:27:47]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[website] [2023-03-27 14:27:47]       at async getTokenMeta (/workspace/.next/server/chunks/6543.js:80:22)
[website] [2023-03-27 14:27:47]       at async processor (/workspace/.next/server/chunks/6509.js:29:27)
[website] [2023-03-27 14:27:47]       at async Promise.all (index 14)
[website] [2023-03-27 14:27:47] }
[website] [2023-03-27 14:27:47] node:internal/process/promises:279
[website] [2023-03-27 14:27:47]             triggerUncaughtException(err, true /* fromPromise */);
[website] [2023-03-27 14:27:47]             ^
[website] [2023-03-27 14:27:47] 
[website] [2023-03-27 14:27:47] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
[website] [2023-03-27 14:27:47]   code: 'ERR_UNHANDLED_REJECTION'
[website] [2023-03-27 14:27:47] }
[website] [2023-03-27 14:27:47]
