### ISSUE TITLE
O botão de troca para Brasileiro não funciona, quando eu clico não é gerada nenhuma requisição nem atualização no site

### ISSUE THREAD

**Issue by JaoDuque** [simbiotica-finance/bug-bounty#15]
![Captura de tela 2023-03-24 225617](https://user-images.githubusercontent.com/107492575/227679952-21399507-100e-4428-91be-8eb678b4eeb5.png)

**Comment by dav1app** [comment]
Closing in favour of #8. 

Veja quem fica com a recompensa.

**Comment by JaoDuque** [comment]
Lucas
